import Head from "next/head.js";
import Header from "./Header.js";

const Layout = ({ children, title }) => {
  return (
    <>
      <Head>
        <title>{title ? `${title + "- Ecommerce"}` : "Ecommerce"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Header />
      </header>
      <main>{children}</main>
      <footer>Footer</footer>
    </>
  );
};

export default Layout;
